version: '3.2'
services:
  auto_bangumi:
    container_name: AutoBangumi
    environment:
      - TZ=Asia/Shanghai
      - PGID=${GID}
      - PUID=${UID}
    networks:
      - auto_bangumi
    ports:
      - '7892:7892'
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    dns:
      - 8.8.8.8
      - 223.5.5.5
    restart: unless-stopped
    image: estrellaxd/auto_bangumi:latest

networks:
  auto_bangumi:
volumes:
  auto_bangumi:
    external: false
