version: '3.2'
services:
  auto_bangumi:
    container_name: AutoBangumi
    environment:
      - TZ=Asia/Shanghai
      - PGID=${GID}
      - PUID=${UID}
      - AB_DOWNLOADER_HOST=localhost:${QB_PORT}
      - AB_DOWNLOADER_USERNAME=admin
      - AB_DOWNLOADER_PASSWORD=adminadmin
      - AB_DOWNLOAD_PATH=${DOWNLOAD_PATH}
      - AB_RSS=${RSS}
    networks:
      - auto_bangumi
    ports:
      - '7892:7892'
    volumes:
      - auto_bangumi:/config
    dns:
      - 8.8.8.8
      - 223.5.5.5
    restart: unless-stopped
    image: estrellaxd/auto_bangumi:latest

networks:
  auto_bangumi:
volumes:
  auto_bangumi:
    external: false
