version: "3.2"
services:
  qbittorrent:
    container_name: qBittorrent
    environment:
      - TZ=Asia/Shanghai
      - TemPath=/downloads
      - SavePath=/downloads
      - PGID=${GID}
      - PUID=${UID}
      - WEBUI_PORT=${QB_PORT}
    volumes:
      - qb_config:/config
      - ${DOWNLOAD_PATH}:/downloads
    ports:
      - ${QB_PORT}:${QB_PORT}
      - 6881:6881
      - 6881:6881/udp
    networks:
      - auto_bangumi
    restart: unless-stopped
    image: superng6/qbittorrent:latest

  auto_bangumi:
    container_name: AutoBangumi
    environment:
      - TZ=Asia/Shanghai
      - PGID=${GID}
      - PUID=${UID}
      - AB_DOWNLOADER_HOST=qbittorrent:${QB_PORT}
    networks:
      - auto_bangumi
    volumes:
      - /path/to/config:/app/config
      - /path/to/data:/app/data
    ports:
      - 7892:7892
    dns:
      - 8.8.8.8
      - 223.5.5.5
    restart: unless-stopped
    image: estrellaxd/auto_bangumi:latest
    depends_on:
      - qbittorrent

  plex:
    container_name: Plex
    environment:
      - TZ=Asia/Shanghai
      - PUID=${UID}
      - PGID=${GID}
      - VERSION=docker
    networks:
      - auto_bangumi
    ports:
      - 32400:32400
    volumes:
      - plex_config:/config
      - ${DOWNLOAD_PATH}/Bangumi:/tv
    restart: unless-stopped
    image: lscr.io/linuxserver/plex:latest

networks:
  auto_bangumi:

volumes:
  qb_config:
    external: false
  plex_config:
    external: false

